site_name: Qadence 2 Platforms
repo_url: "https://github.com/pasqal-io/qadence2-platforms"
repo_name: "qadence2_platforms"

nav:
  - Home: index.md

  - Getting started:
    - Installation: getting_started/installation.md
    - Example: getting_started/example.md
    - Development & Info:
      - Contributing: getting_started/CONTRIBUTING.md
      - Code of conduct: getting_started/CODE_OF_CONDUCT.md
      - License: getting_started/LICENSE.md

  - Contents:
    - contents/index.md
    - Abstracts: contents/abstracts.md
    - Compiler: contents/compiler.md
    - Backends: contents/backends.md
    - Utils: contents/utils.md

  - Tutorials:
    - Tutorials: tutorials/examples.md
    - Building your backend: tutorials/backend_creation.md

  - API:
    - api/index.md
    - Abstracts: api/abstracts.md
    - Compiler: api/compiler.md
    - Backends:
      - api/backends/index.md
      - Fresnel-1:
        - api/backends/fresnel1/index.md
        - Interface: api/backends/fresnel1/interface.md
        - Compiler: api/backends/fresnel1/compiler.md
        - Functions: api/backends/fresnel1/functions.md
        - Register: api/backends/fresnel1/register.md
        - Sequence: api/backends/fresnel1/sequence.md
      - Analog:
        - api/backends/analog/index.md
        - Interface: api/backends/analog/interface.md
        - Compiler: api/backends/analog/compiler.md
        - Functions: api/backends/analog/functions.md
        - Register: api/backends/analog/register.md
        - Sequence: api/backends/analog/sequence.md
      - Abstract analog backend:
        - api/backends/_base_analog/index.md
        - Interface: api/backends/_base_analog/interface.md
        - Functions: api/backends/_base_analog/functions.md
        - Register: api/backends/_base_analog/register.md
        - Sequence: api/backends/_base_analog/sequence.md
        - Device Settings: api/backends/_base_analog/device_settings.md
      - PyQTorch:
        - api/backends/pyqtorch/index.md
        - Interface: api/backends/pyqtorch/interface.md
        - Compiler: api/backends/pyqtorch/compiler.md
        - Functions: api/backends/pyqtorch/functions.md
        - Register: api/backends/pyqtorch/register.md
        - Embedding: api/backends/pyqtorch/embedding.md
    - Utils:
      - api/utils/index.md
      - Backend Template: api/utils/backend_template.md
      - Module Importer: api/utils/module_importer.md


theme:
  name: material
  custom_dir: docs/extras/overrides
  features:
  - content.code.annotate
  - content.action.view
  - content.action.edit
  - navigation.tabs
  - navigation.indexes
  - navigation.sections
  - content.code.copy

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: light green
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: light green
    toggle:
      icon: material/weather-night
      name: Switch to light mode

markdown_extensions:
- admonition  # for notes
- footnotes
- pymdownx.arithmatex: # for mathjax
    generic: true
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.details
- pymdownx.superfences:
    custom_fences:
    - name: python
      class: python
      validator: "!!python/name:markdown_exec.validator"
      format: "!!python/name:markdown_exec.formatter"

plugins:
- search
- section-index
- markdown-exec
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        selection:
          filters:
            - "!^_"  # exlude all members starting with _
            - "^__init__$"  # but always include __init__ modules and methods
        options:
          show_root_toc_entry: false
          heading_level: 3
          merge_init_into_class: true
          docstring_section_style: spacy
- mike:
    deploy_prefix: ''
    version_selector: true

watch:
  - qadence2_platforms

extra:
 version:
   default: stable

# To get nice tabs
extra_css:
- css/mkdocstrings.css
- extras/css/colors.css
- extras/css/home.css

# For mathjax
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
